@startuml
'https://plantuml.com/class-diagram

abstract class GameLoop
class GameControllerForTTT
class ClientConnectionController
class Player
class Board
class Stones
class TicTacToeGameLoop
class DesicionTree
class Settings
class SharedData

TicTacToeGameLoop <|-- GameLoop
GameLoop <|--  ClientConnectionController
GameLoop .> GameStatus : > depends
GameLoop <|-- GameControllerForTTT

ClientConnectionController <|-- Settings
ClientConnectionController <|-- SharedData

Player - GameControllerForTTT
GameControllerForTTT <.. DesicionTree : > depends
GameControllerForTTT <.. Board : > depends
Board *-- Stones : needs >











abstract class GameLoop {
}

enum GameStatus {
RUNNING
STOPPED
}

@enduml